### ISSUE TITLE
Link ABAP SDK for Azure

### ISSUE THREAD

**Issue by MartinPankraz** [microsoft/aisdkforsapabap#10]
Our generalizes ABAP SDK offerings and customers would profit from discoverability if cross-referenced here. Please add a callout that other Azure services can be consumed using that: https://github.com/microsoft/ABAP-SDK-for-Azure

**Comment by gopalnair** [comment]
Moving this to internal discussion -  so that we can find the right place in documentation for the call out. 
The Documentation is currently in progress at : [AI SDK Documentation](https://microsoft.github.io/aisdkforsapabap/).
