### ISSUE TITLE
Error while installing SDK

### ISSUE THREAD

**Issue by vinayakgole78** [microsoft/aisdkforsapabap#21]
Hi,
While installing the SDK, we get the attached error. Please advise.
![image](https://github.com/microsoft/aisdkforsapabap/assets/98078228/63e101c3-9a92-4174-9577-919005053b2e)

Thank you
Vinayak

**Comment by gopalnair** [comment]
Hi @vinayakgole78 ,
   It seems, your ABAP Git program (ZABAPGIT_STANDALONE) is out dated. Could you please try installing the latest version of ABAP Git ([Video tutorial here ](https://microsoft.github.io/aisdkforsapabap/docs/sdk-installation/installing-sdk)) 

Please let me know if the issue persists after installing latest version of ABAP Git. 

Best REgards,
Gopal Nair.

**Comment by vinayakgole78** [comment]
Thank you for the prompt response @gopalnair 
I have highlighted to the BASIS team. I shall reach out in case of further roadblocks.

Regards
Vinayak
