### ISSUE TITLE
Thanks Gopal for quick response. I tried creating Secret Key and use in the program ZP_PENGG_AZOAI_DEMO_COMPLETION. But what will be the input for other Selection Screen Parameters?

### ISSUE THREAD

**Issue by Dev4Develop** [microsoft/aisdkforsapabap#22]
Thanks Gopal for quick response. I tried creating Secret Key and use in the program ZP_PENGG_AZOAI_DEMO_COMPLETION. But what will be the input for other Selection Screen Parameters?

Otherwise If we have any demo program without Azure let me know.

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/e418cf34-5a5a-4b87-a7d4-80343a677fc1)

_Originally posted by @Dev4Develop in https://github.com/microsoft/aisdkforsapabap/issues/20#issuecomment-1653235325_

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
  For the Base URL and Key, please refer to this [documentation](https://microsoft.github.io/aisdkforsapabap/docs/Initial%20Setup/azure-open-ai/azoai-key-endpoint) 

The Deployment ID would be the name you have given for a GPT-3 model deployment.  (eg: test-davinci-003)
You can give a token length of say, 1500 

To see a demo video of this program, please see this [Youtube Video](https://youtu.be/ms_VFbl8-rY?t=157).

NOTE : There are more video tutorials planned in near future.

**Comment by Dev4Develop** [comment]
What would be the version? I gave v1 and it was saying invalid version. ( Couldn't recollect the exact text )

**Comment by Dev4Develop** [comment]
As shown in screenshot.
**Base URL** here is azure related right? But my azure free trial has been disabled. What to give here? 
**Version** is 2022-12-01
**Key** is Secret Key that I have created in Open AI directly.

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/2aaf722b-caf6-4844-b327-38c88cf1b9d3)

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
   If the azure trial is disabled, the Azure Open AI resource will not work - and you wont be able to run the application using Azure Open AI.

However, as I mentioned before, AI SDK for SAP supports open AI as well. 

I will try and publish a video tutorial on the documentation site (Over the weekend) , which showcase
1) How to set up Open AI authorization key.
2) How to run the demo program using Open AI

Best Regards,
Gopal Nair.

**Comment by Dev4Develop** [comment]
Sure, that helps Gopal.

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
   Please use this link for [Open AI Initial Setup](https://microsoft.github.io/aisdkforsapabap/docs/Initial%20Setup/open-ai/oai-initial-setup)

Once set up, please see [this documentation page to perform a test run](https://microsoft.github.io/aisdkforsapabap/docs/sdk-installation/smoke-testing-openai).


For Open AI, the model name is the deployment ID. Also, the version is "v1", as shown in the test run.

Please let me know how it went.

Best Regards,
Gopal Nair.

**Comment by Dev4Develop** [comment]
Hi Gopal,

Firstly, I couldnt see ZP_MSAISDKDEMO_MODELS_OAI in my list. 
I downloaded repository on Jun 08th
![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/c37bd18a-da8d-42b5-aa4c-bd7707d85f90)

So I chose ZP_MSAISDKDEMO_MODELS.
![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/59c292b0-0825-4fcb-91f1-7610673db56b)

I gave below input
![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/c0c30c85-8398-45ba-a967-10d974e081ec)

Below is the response
![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/92216a43-475f-4c79-ab07-10e762e77baa)

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
   It seems, the incorrect demo program is used here.

1. Please open the [documentation page for Models](https://microsoft.github.io/aisdkforsapabap/docs/working-with-sdk/models).
1. Switch to "Open AI" mode in the documentation. 
![image](https://github.com/microsoft/aisdkforsapabap/assets/1298551/9998a6ad-2c38-4afc-bc15-28c583dd4dad)

1. You will notice that, the entire documentation site has now changed to "Open AI" relevant information. This includes, the demo program name as well. The demo program name for Open AI Models is : **ZP_MSAISDKDEMO_MODELS_OAI**
![image](https://github.com/microsoft/aisdkforsapabap/assets/1298551/69f98513-21e5-4f63-ad36-681070fb4743)

1. As you can see in the documentation, the version for Open AI is "v1".

Please let me know if you run into further issues.

Best Regards,
Gopal Nair.

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
 I missed the first part of your message, where you mentioned, you could not find the program "ZP_MSAISDKDEMO_MODELS_OAI" in your system.

Could you please try pulling the "main" branch again, so that the latest code is pulled and installed into your system?

Please let me know how it goes.

Best Regards,
Gopal Nair.

**Comment by Dev4Develop** [comment]
Hi Gopal,

1. I tried **ZP_MSAISDKDEMO_MODELS_OAI.** 

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/30c6440c-0a70-4b0f-8634-6fdb7ae57f61)
It says "Version Not Supported"
![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/d5fb0a1d-066b-4e5e-bf41-7b1f4dc85409)

2. Then I tried **ZP_MSAISDKDEMO_COMPLETION_OAI** 

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/37ac29b3-53d7-4f2f-a43a-53b5a3817db1)

same message

![image](https://github.com/microsoft/aisdkforsapabap/assets/137146462/fdcdc6da-8d8a-4e01-82d6-7e14b69ca50a)

**Comment by gopalnair** [comment]
Hi @Dev4Develop ,
 This is interesting. I double checked by running the model demo program for Open AI, with version "v1" (The default that comes up), and everything worked OK.

How about we meet at some time, so that I can look in your system?

Best Regards,
Gopal Nair.

**Comment by Dev4Develop** [comment]
Sure. We can check. Our Demo system is available only on Tue, Wed, Thursdays. 
Will be better if we can connect some time today or else we have to wait for next week.
