### ISSUE TITLE
List of Models in Azure Open AI is not matching with what I can see in SAP Debugger

### ISSUE THREAD

**Issue by shreyashagrwl** [microsoft/aisdkforsapabap#33]
Hi Gopal,

I am at **Installing the SDK --> First Test Run - Azure Open AI** step. In the step it asks to compare the list of models present in Azure Open AI Studio with the one seen in the SAP debugger. In my case, the model list isn't matching, what could have gone wrong?
Image from Azure Open AI Studio - 
![image](https://github.com/microsoft/aisdkforsapabap/assets/146458948/daeb162c-47cf-41c5-a850-f6f52380a72e)

 Image from SAP Debugger - 
![image](https://github.com/microsoft/aisdkforsapabap/assets/146458948/51a37c9b-f788-4674-8701-22f7df55016c)

**Comment by gopalnair** [comment]
Hi @shreyashagrwl ,
  I have to admit, I do not know the exact reason for this. I have observed this as well.

AI SDK for SAP uses REST API to query the list of models from AI Engine endpoint. The list in the debugging session is received from the AI Endpoint, as the available models.

However, when going through the web interface, a subset of this list is what gets presented. I have tried to see if there are any specific parameters that are being filtered in the web interface - but have not figured it out yet.

If/When I do eventually figure it out, I will be sure to put a response here.

Best Regards,
Gopal Nair.
