### ISSUE TITLE
TY_ERROR ?

### ISSUE THREAD

**Issue by larshp** [microsoft/aisdkforsapabap#6]
Hi,
Looks like https://github.com/microsoft/aisdkforsapabap/blob/main/src/zpengg_ai_openai_main/zpengg_ai_openai_azure/zpengg_ai_openai_azure_sdk/zpengg_azoai_sdk_core/zif_peng_azoai_sdk_types.intf.abap#L120 refers to the SAP DDIC type TY_ERROR? Which is part of SAP component FI-AP-AP-Q1

I guess you want to refer to the type https://github.com/microsoft/aisdkforsapabap/blob/main/src/zpengg_ai_openai_main/zpengg_ai_openai_azure/zpengg_ai_openai_azure_sdk/zpengg_azoai_sdk_core/zif_peng_azoai_sdk_types.intf.abap#L167 instead?

![image](https://user-images.githubusercontent.com/5888506/233777375-385194f7-a514-4706-9ffc-5f7f191017b2.png)

**Comment by gopalnair** [comment]
Thank you @larshp .

The field should point to : zif_peng_azoai_sdk_typinternal=>ty_internal_error_object

![image](https://user-images.githubusercontent.com/1298551/233800141-7df5acb2-a065-45da-86b2-9357e0c4099d.png)

I have corrected the code and updated main branch. 

If you could pull the latest, and confirm resolution, we can close this issue.

Best Regards,
Gopal Nair.

**Comment by larshp** [comment]
looks good, thanks, closing
